sequenceDiagram
    participant C as Cliente
    participant R as app.routes
    participant F as app.factura_electronica
    participant P as pyafipws
    participant A as AFIP

    C->>R: POST /api/afipws/facturador (con JSON)
    activate R
    R->>F: facturar(json_data)
    activate F
    F->>P: WSAA.Autenticar()
    activate P
    P->>A: Solicitar Token de Acceso
    A-->>P: Token de Acceso
    P-->>F: Token de Acceso (TA)
    deactivate P
    
    F->>F: new Comprobante(json_data)
    F->>F: comprobante.autorizar(wsfev1)
    activate F
    
    F->>P: wsfev1.CrearFactura(...)
    F->>P: wsfev1.CAESolicitar()
    activate P
    P->>A: Solicitar CAE
    A-->>P: CAE y Datos de Autorización
    P-->>F: wsfev1.CAE, wsfev1.Vencimiento, etc.
    deactivate P
    
    deactivate F
    F-->>R: JSON con CAE y nro_comprobante
    deactivate F
    R-->>C: JSON Response
    deactivate R
